name: fitora_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  logger: ^2.5.0
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  animations: ^2.0.11
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  connectivity_plus: ^6.1.0
  flutter_svg: ^2.0.16
  video_player: ^2.9.2
  image_picker: ^1.1.2
  youtube_player_flutter: ^9.1.1
  google_sign_in: ^6.2.2
  go_router: ^14.8.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  infinite_scroll_pagination: ^4.1.0
  image_cropper: ^9.0.0
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/vectors/
    - assets/svg/
    - .env

#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/logo.png
#  fullscreen: true
#  android: true
#  ios: true